export enum ActionType {
  API_GET = 'API_GET',
  ADD_GROCERY = 'ADD_GROCERY',
  GET_METHOD = 'GET_METHOD',
  SELECTED_ITEM = 'SELECTED_ITEM',
  INPUT_CONTENTS = 'INPUT_CONTENTS',
  DROP_CONTENTS = 'DROP_CONTENTS',
}
