export enum ActionType {
  FETCH_ITEMS = 'FETCH_ITEMS',
  ADD_ITEMS = 'ADD_ITEMS',
  GET_METHOD = 'GET_METHOD',
  SELECTED_ITEM = 'SELECTED_ITEM',
  INPUT_CONTENTS = 'INPUT_CONTENTS',
  DROP_CONTENTS = 'DROP_CONTENTS',
}
